const ADD_TODO = "ADD_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const EDIT_TODO = "EDIT_TODO";
const SAVE_TODO = "SAVE_TODO";
const CLEAR_TODO = "CLEAR_TODO";
const SET_INPUT_VALUE = "SET_INPUT_VALUE";
const EDIT_ID = "EDIT_ID";

export {
  SET_INPUT_VALUE,
  ADD_TODO,
  REMOVE_TODO,
  EDIT_TODO,
  SAVE_TODO,
  CLEAR_TODO,
  EDIT_ID
};
